### PR TITLE
Fix datetime field scan error into dummy with "parseTime=true" (Scan pai...

### PR DESCRIPTION
**Pull request by d-g-laptev**
"sql: Scan error on column index 13: unsupported driver -> Scan pair: time.Time -> *sql.RawBytes"" occurs when datetime fields doesn't exists in struct, but exists in DB-table and i have "?loc=Local&parseTime=true" additional connection params.
So i add custom struct for dummy fields, that implements Scanner interface

### CODE REVIEW

**Comment by GeertJohan** [comment]
I think you shouldn't select a field if it's not going to be scanned into your struct.
Can you give an example of a case where this problem happens, or maybe provide PR with a failing test case?

**Comment by d-g-laptev** [comment]
Sometimes easier to SELECT * (if we must select a lot of fields, except several)
And if one of skipped fields will be DATETIME and parseTime is true, it will cause an error, because sql.RawBytes doesn't implemet Scanner interface

**Comment by GeertJohan** [comment]
I'm adding tests about time, also added a parseTime=true run in the automated testing for mysql. #226
Could you provide a failing test case for this with parseTime=true?

**Comment by GeertJohan** [comment]
I'm not sure we should ignore unused values. There is an issue about generating a select statement with just the fields you need. See #133. Using `select *` is bad practice, especially when not reading all fields.. Furthermore, this PR now also contains `SelectMapCollection()` and other stuff, I guess that is because you used the master branch and added more commits to it for personal use. Do you think a solution for #133 would be sufficient for your use-case?

**Comment by GeertJohan** [comment]
Merged through #277

**Pull request closed without merging**
