### PR TITLE
Add explicit note about Postgres and  / ? placeholders in README.md

### PR DESCRIPTION
**Pull request by jsanc623**
https://github.com/go-gorp/gorp/issues/243

### CODE REVIEW

**Comment by nelsam** [comment]
Quick thought: Could we maybe add a note about `Dialect.BindVar`?  Something like:

`Alternatively, use dbMap.Dialect.BindVar(varIdx) to get the proper variable binding for your dialect.`

**Comment by jsanc623** [comment]
Good call @nelsam. Updated with your note

**Comment by nelsam** [comment]
Cool, thanks.  This looks good to me; but I haven't had much sleep, so I don't want to merge it until I'm fully woken up.

**Comment by jsanc623** [comment]
not a problem @nelsam  :) thanks! :+1:

**Comment by GeertJohan** [comment]
LGTM but I'm also very tired..
Maybe squash the commits for a cleaner history?
Thanks @jsanc623!

**Comment by jsanc623** [comment]
Thanks for the heads up on squash @GeertJohan - should be good now :+1:

**Comment by nelsam** [comment]
@jsanc623 It looks like your squash didn't quite work - the history still contains all of the previous commits, as well.  Can you try again following [this guide](http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit)?

**Comment by GeertJohan** [comment]
Merged in 27556ff8f1124b8aaa7926f11ac7ec2c4d62bf61

**Pull request closed without merging**
