### PR TITLE
Support default value.

### PR DESCRIPTION
**Pull request by zallwu**
Support default value. (i.e. "uuid()", "uuid_short()", etc).

### CODE REVIEW

**Comment by GeertJohan** [comment]
Please add test cases and re-open this PR on master branch (we've deprecated the `develop` branch)

**Comment by GeertJohan** [comment]
@zallwu If you could add a testcase and docs then we could merge this at `v2-phase1` (see #270). Otherwise we'll have to postphone it to `v2.1`, at which point the codebase will have changed a lot.

**Comment by GeertJohan** [comment]
@zallwu If you could add a testcase and docs, as well as rebase to master, then we could merge this at `v2-phase1` (see #270). Otherwise we'll have to postphone it to `v2.1`, at which point the codebase will have changed a lot.

**Comment by GeertJohan** [comment]
Looked at the code again. I think it would be better to add default as a part of the db tag:
`db:"name, default:uuid()"`

**Comment by GeertJohan** [comment]
I'll merge and add open an issue so we can work it out in phase3.

**Comment by GeertJohan** [comment]
Merged at 96583e83d36be671cc76657afdc7f61ba5986661

**Comment by GeertJohan** [comment]
Actually added the default option to the db tag just now..

**Comment by wzzhu** [comment]
This is not completed. Should add the patch below:

--- a/table.go
+++ b/table.go
@@ -211,6 +211,9 @@ func (t *TableMap) SqlForCreate(ifNotExists bool) string {
                        if col.Unique {
                                s.WriteString(" unique")
                        }
+                       if col.DefaultValue != "" {
+                               s.WriteString(fmt.Sprintf(" default %s", col.DefaultValue))
+                       }
                        if col.isAutoIncr {
                                s.WriteString(fmt.Sprintf(" %s", dialect.AutoIncrStr()))
                        }

**Pull request closed without merging**
