### PR TITLE
Added an "upsert" mechanism and associated unittests.

### PR DESCRIPTION
**Pull request by spencerkimball**
Upsert is a portmanteau for "update" and "insert". It allows a single
statement to either insert if the primary key is not presetn or update
if it is present.

The current implementation is MySQL specific and will return an error
for any other dialect. Support for this feature varies widely amongst
database vendors as it's not part of the SQL ansi standard. For MySQL,
we use the "ON DUPLICATE KEY UPDATE ..." suffix to insert statements.

### CODE REVIEW

**Comment by GeertJohan** [comment]
I would still like to see this feature. I think a transaction with select by primary key, then insert or update would work..

**Comment by GeertJohan** [comment]
"Upsert" is a good name, I think it's very descriptive. Any plans to make this work @spencerkimball ?

**Comment by spencerkimball** [comment]
I'm not currently working with gorp, so no immediate plans to add this feature.

**Comment by GeertJohan** [comment]
I'm closing this PR for now (see #270). However, I would still like to see this feature so #130 will stay open and there's a good chance I'll re-use code from this PR to add the feature after `v2.0`/#270

**Pull request closed without merging**
