### PR TITLE
Update gorp.go

### PR DESCRIPTION
**Pull request by sqdk**
Added warning telling users that automatic mapping of Version struct members to version column in database (optimistic locking) will be removed in V2.

See PR: https://github.com/go-gorp/gorp/pull/214

### CODE REVIEW

**Comment by GeertJohan** [comment]
Hmm I don't think we should log to stdout because some programs use stdout for inter-process communication. Maybe use the Dbmap.logger for this?

**Comment by sqdk** [comment]
Using Dbmap.logger will only show the warning if the logger is explicitly enabled and it will generate a lot of text that might make it hard to see (like the query log).

I can change output to std.err

**Comment by GeertJohan** [comment]
Maybe it's better to create a migration guide/document where we note all breaking changes between v1 and v2. That way we don't interrupt v1 users, and they will have to go through such a guide anyway when migrating from v1 to v2.

**Comment by sqdk** [comment]
That's a nice way to do it. All good now?

**Comment by GeertJohan** [comment]
Yes! Release as v1.7.1? (patch +1)

**Comment by sqdk** [comment]
Sounds good!

**Comment by GeertJohan** [comment]
Created `v1` branch as `gopkg-in-releases` is a strange name. Tagged v1.7.1 which is now the latest v1: http://gopkg.in/gorp.v1

**Pull request merged**
