### PR TITLE
Do not force convert Postgres's table/field names to lower case. Fixes #119, #192.

### LINKED ISSUE #119: To lower in PosgresDialect
`func (d PostgresDialect) QuoteField(f string) string`

Why this function use strings.ToLower ?
`return " + strings.ToLower(f) + "`

I had to fix this in order to use datables with camelcase, like helloWorld.

With this function, datatable "helloWorld" become "helloworld" and it becomes impossible to use this datable with gorp ?

### PR DESCRIPTION
**Pull request by vinceyuan**
To use lower case table name in Postgres, do something like this: `dbmap.AddTableWithName(Post{}, "posts")`
To use lower case field name in Postgres, specify the field name in type definition: ``type Post struct { Title   string `db:"title"` }``

Tested getting, creating, updating, deleting objects in Postgres.

### CODE REVIEW

**Comment by vinceyuan** [comment]
Any comments?

**Comment by vinceyuan** [comment]
Any response?

**Comment by nelsam** [comment]
Your tests aren't passing on travis ... do you know why?

Sorry, I've been absent a lot lately due to my job having a lot of changes (new office, different hours, etc).  I'll check on it as soon as I get a chance.

**Comment by vinceyuan** [comment]
@nelsam It's about the field name, e.g. `id` vs `Id`. Let me try to fix it.

**Comment by vinceyuan** [comment]
Test is ok on my mac, but failed in Travis CI. I think it's because mysql's table name and column name are case insensitive on Mac. Let me revert my commit and find a new solution.

**Comment by vinceyuan** [comment]
Reverted my previous commit ff249b53901546511b8acd33ca87568f91db1cdf. Fixed 3 test cases by using quoted column name and table name in the raw SQL. There will be a lot to fix. I will do it tomorrow (actually today. It's 3am now).

**Comment by nelsam** [comment]
Cool; thanks for all your work, @vinceyuan.  Again, sorry for the late response - I'll do my best to stay on top of *this* PR, at least.

**Comment by vinceyuan** [comment]
@nelsam Done. Don't know why test for go1.2 failed on Travis. Other tests are good.

**Comment by nelsam** [comment]
@vinceyuan Looks fine to me.  Let me check with the other maintainers, but my initial thought is to deprecate go 1.2.  That's pretty old at this point.

**Comment by vinceyuan** [comment]
@nelsam Great, thanks. This PR may break existing projects which use Postgres, because table name and column name are no longer lower case by default.

To use lower case table name in Postgres, do something like this: dbmap.AddTableWithName(Post{}, "posts")

To use lower case field name in Postgres, specify the field name in type definition: type Post struct { Title string `db:"title"` }

 I have a little to submit to make benchmark work for postgres.

**Comment by nelsam** [comment]
Yeah; we're supporting `gopkg.in` for backwards compatibility.  Anyone relying on master at this point should know that their code might break because of us.

We'll double check the documentation on merge, though.

**Comment by GeertJohan** [comment]
This PR is not building on travis... A rebase could work?

**Comment by GeertJohan** [comment]
@vinceyuan

**Comment by vinceyuan** [comment]
@GeertJohan What do you mean? This PR passed Go:1.3/1.4/tip, but did not pass Go:1.2 on travis-ci.

**Comment by GeertJohan** [comment]
Sorry for the late late reply.

It looks like `github.com/mattn/go-sqlite3` dropped go1.2 support, as did we by the way.
If you could rebase on master, the tests on travis-ci will be without 1.2.

**Comment by vinceyuan** [comment]
Rebased. @GeertJohan Thanks!

**Comment by GeertJohan** [comment]
Thanks @vinceyuan !

**Comment by vinceyuan** [comment]
@mauleyzaola This is the breaking change, which I believe will be included in v2.0. The current stable release is v1. (Use `import "gopkg.in/gorp.v1"` in the project)

As mentioned in the commit comment, 

To use lower case table name in Postgres, do something like this: `dbmap.AddTableWithName(Post{}, "posts")`
To use lower case field name in Postgres, specify the field name in type definition: ``type Post struct { Title string `db:"title"` }``

Because there are 1747 fields in your project, it will be labour intensive to modify the existing code. Sorry for it.

**Comment by mauleyzaola** [comment]
@vinceyuan No worries, it is doable and thanks for the info :+1: I was just little upset when I wrote that :smile:

**Comment by GeertJohan** [comment]
@mauleyzaola Sorry for breaking your build. I hope most people have updated to the v1 on gopkg.in by now. I've actually manually contacted all public projects using gorp and asked them to update to gopkg.in, but I'm sure there are still some private projects using the master branch. I hope updating isn't too much of a problem for you. Cheers!

**Pull request merged**
