### PR TITLE
Remove automatic mapping of version column (optimistic locking)

### PR DESCRIPTION
**Pull request by sqdk**

### CODE REVIEW

**Comment by sqdk** [comment]
I think that the mysql driver is not compatible with Go 1.1, which is why Travis is failing.

**Comment by GeertJohan** [comment]
I would actually be in favor of only supporting the last 2 minor releases, so 1.3.x and 1.4.x.
Maybe we should open an issue for this to poll support?

**Comment by sqdk** [comment]
Sure, sounds good. I'm not sure about the format, so could you create the poll?

Do you think that this PR should just be merged and then we can update .travis.yml when we agree on what versions to support?

**Comment by GeertJohan** [comment]
Well if we merge this, then all other builds will fail and we'll have to manually inspect what fails.
So I'd rather see the travis config updated first to fix the build. I think we can drop support for 1.1 right now, and I'll open a poll issue about the policy.

**Comment by sqdk** [comment]
I have updated travis to only support the last 2 minor releases. When the poll is finished it should be ready to be merged.

**Comment by GeertJohan** [comment]
I've changed the .travis.yml already in a different PR to do 1.2 (best effort), 1.3 and 1.4.

I think this PR needs a rebase and squash, it's a bit dirty with all the merge commits.

**Comment by sqdk** [comment]
I think that all should be good now. First time squashing and rebasing though. Please let me know if anything could be done in a better way.

**Comment by GeertJohan** [comment]
Yes, lets merge it in when build succeeds :smile: 
What do you think about adding this functionality as a struct tag option too?
I think it's good to have a consistent user experience to alter dbmapping options such as primary key and autoincrement and version..

**Comment by sqdk** [comment]
That would be a very good idea! I can maybe take a look at it later today or tomorrow :smiley:

**Pull request merged**
