### PR TITLE
Added primarykey and autoincrement in the field tag

### PR DESCRIPTION
**Pull request by meetmauro**
OK, rebased on master, used attributes in the same db tag and renamed pk to primarykey.
I tested the PR in my projects too and all seems to be working.

### CODE REVIEW

**Comment by GeertJohan** [comment]
The tests failed with
```
--- FAIL: TestCrud (0.01s)

gorp_test.go:1092: val.GetId() was not set on INSERT
```

Any thoughts why this happens?

**Comment by meetmauro** [comment]
Let me check. For the tests I did it seemed to behave.

**Comment by meetmauro** [comment]
OK :) forgot to add the autoincrement label in the tests, now it seems to be passing

**Comment by sqdk** [comment]
This would conflict with changes made in PR #224, more specifically in readStructColumns(). I think reading tags should be kept in this function, and version should be added to tags through here as well. 

If you could extend it to also read the version column from tags it should be pretty easy to merge.

**Comment by GeertJohan** [comment]
@meetmauro Can you make the changes requested by @sqdk? If so we can still merge this in in at `v2-phase1` (see #270), otherwise it will be v2.1, and at that point the codebase will have changed a lot!

**Comment by GeertJohan** [comment]
I'll merge right now.

**Pull request merged**
