### PR TITLE
Added returning data to a channel of pointers to DbMap.Select()

### PR DESCRIPTION
**Pull request by JonPulfer**
Hi,

I have added the capability to pass in a channel (which takes pointers to structs) to the DbMap.Select() method. This enables large tables to be processed in a stream.

Kind regards,
Jon

### CODE REVIEW

**Comment by GeertJohan** [comment]
@JonPulfer I'm very interested in this feature, but sadly the PR seems to be messed up a bit.
I think the feature could be best added in a new `SelectFoobar` method. 
We're now cleaning up the issue and PR backlog (see #270), so I think this feature would best be added after we're done with that. I think it will require a new PR as at that point code will be separated into multiple files and more changes applied. Keeping this PR open so we will look at it again. Please let me know if you're still interested in seeing this merged.

**Comment by JonPulfer** [comment]
Hi Geert-Johan,

I found it useful for the task I created it for, I submitted the PR in case it was something others would find useful. I can look at creating a new PR from current develop branch if that would help?

Kind regards,
Jon

**Comment by GeertJohan** [comment]
We've stopped using the `develop` branch, all development now takes place at `master`. I think it would be best to wait until we have cleaned up the codebase and have released v2, that will also make development easier for you.

**Comment by JonPulfer** [comment]
Ok, I will watch out for that release.

Kind regards,
Jon

**Comment by nelsam** [comment]
fwiw, I still think this would be useful (esp. for automatic pagination of queries) in a later version.  Development on gorp in general is sluggish right now, but if/when we get to that point, we'll definitely come back to the idea.

In the mean time, I'm going to close this issue.

**Pull request closed without merging**
